# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable daily updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Dependabot knows to look in .github/workflows for GitHub Actions
    schedule:
      interval: "daily"

  # Enable daily updates for Docker
  - package-ecosystem: "docker"
    directory: "/.docker" # Location of Dockerfile
    schedule:
      interval: "daily"
